on: [push, pull_request]
name: Test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint Code Base
      uses: docker://github/super-linter
      env:
        # VALIDATE_ALL_CODEBASE: false
        VALIDATE_ANSIBLE: false
  test_packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: artifacts.pkr.json packer.json